#!/usr/bin/env python3
"""Aggregate runner for research/quantum-erdos-sequences/sequences/*.py.

Addresses a reproducibility gap flagged in review: the per-lane scripts use
inconsistent entry-point conventions (some call sys.exit with the verdict,
most do not), so a process exit code alone cannot be trusted as the verdict
signal across all 999 lanes. This runner instead:

  1. Executes each lane as its own subprocess (so one lane crashing cannot
     corrupt another's state), with a fixed timeout.
  2. Treats a nonzero interpreter exit OR an uncaught traceback in stdout/
     stderr as ran_ok=False (the lane did not execute cleanly).
  3. Parses the lane's own reported PASS/FAIL verdict from stdout (lanes
     report it in varied forms -- bare "PASS", "RESULT: PASS",
     "PASS: <explanation>" -- so this scans for PASS/FAIL as a whole word,
     from the end of stdout, rather than requiring an exact line).
  4. Writes machine-readable RESULTS.json and a regenerated RESULTS.md
     table, and exits nonzero if any lane failed to run or failed
     verification -- so the totals this file reports are the ones this
     script can actually reproduce and enforce, not a hand-maintained claim.

Usage:
    python3 run_all.py                 # run all lanes, write RESULTS.json/.md
    python3 run_all.py --lane 123       # run a single lane by problem number

Dependencies: see requirements.txt (qiskit, qiskit-aer, numpy). Shots are
not seeded in the individual lane scripts, so re-running can shift a
borderline lane's measured fraction; PASS/FAIL for the large majority of
lanes is not close to any threshold and is stable across reruns.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

SEQUENCES_DIR = Path(__file__).parent / "sequences"
RESULTS_JSON = Path(__file__).parent / "RESULTS.json"
RESULTS_MD = Path(__file__).parent / "RESULTS.md"
TIMEOUT_SECONDS = 120

# Lanes report their verdict in varied forms ("PASS", "RESULT: PASS",
# "PASS: <explanation>", etc.) -- match PASS/FAIL as a whole word anywhere
# in a line, scanning from the end of stdout, rather than requiring an
# exact bare "PASS"/"FAIL" line.
VERDICT_RE = re.compile(r"\b(PASS|FAIL)\b")


def lane_number(path: Path) -> int:
    m = re.match(r"problem_(\d+)\.py$", path.name)
    return int(m.group(1)) if m else -1


def run_lane(path: Path) -> dict:
    number = lane_number(path)
    start = time.monotonic()
    try:
        proc = subprocess.run(
            [sys.executable, str(path)],
            cwd=str(path.parent),
            capture_output=True,
            text=True,
            timeout=TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return {
            "number": number,
            "file": path.name,
            "ran_ok": False,
            "verified_against_classical": False,
            "verdict": "TIMEOUT",
            "duration_s": TIMEOUT_SECONDS,
        }

    duration = time.monotonic() - start
    stdout = proc.stdout or ""
    stderr = proc.stderr or ""

    crashed = proc.returncode not in (0, 1) or "Traceback (most recent call last)" in stderr

    verdict = None
    for line in reversed(stdout.splitlines()):
        m = VERDICT_RE.search(line)
        if m:
            verdict = m.group(1)
            break

    ran_ok = not crashed and verdict is not None
    verified = ran_ok and verdict == "PASS"

    return {
        "number": number,
        "file": path.name,
        "ran_ok": ran_ok,
        "verified_against_classical": verified,
        "verdict": verdict or ("CRASH" if crashed else "NO_VERDICT_PRINTED"),
        "returncode": proc.returncode,
        "duration_s": round(duration, 2),
    }


def write_results(results: list[dict]) -> None:
    RESULTS_JSON.write_text(json.dumps(results, indent=2, sort_keys=False) + "\n")

    total = len(results)
    ran_ok = sum(1 for r in results if r["ran_ok"])
    verified = sum(1 for r in results if r["verified_against_classical"])
    failed = [r for r in results if not r["verified_against_classical"]]

    lines = [
        "# RESULTS (generated by run_all.py -- do not hand-edit)",
        "",
        f"- Lanes attempted: {total}",
        f"- ran_ok (executed cleanly, printed a PASS/FAIL verdict): {ran_ok}",
        f"- verified_against_classical (printed PASS): {verified}",
        "",
    ]
    if failed:
        lines.append("## Lanes not verified this run")
        lines.append("")
        lines.append("| # | file | verdict |")
        lines.append("|---|------|---------|")
        for r in sorted(failed, key=lambda r: r["number"]):
            lines.append(f"| {r['number']} | {r['file']} | {r['verdict']} |")
        lines.append("")
    RESULTS_MD.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lane", type=int, default=None, help="run a single lane by problem number")
    args = parser.parse_args()

    lanes = sorted(SEQUENCES_DIR.glob("problem_*.py"), key=lane_number)
    if args.lane is not None:
        lanes = [p for p in lanes if lane_number(p) == args.lane]
        if not lanes:
            print(f"No lane found for problem {args.lane}", file=sys.stderr)
            return 2

    results = []
    for path in lanes:
        r = run_lane(path)
        results.append(r)
        print(f"[{r['number']:>4}] {r['file']:<20} ran_ok={r['ran_ok']} verdict={r['verdict']}")

    write_results(results)

    total = len(results)
    verified = sum(1 for r in results if r["verified_against_classical"])
    ran_ok = sum(1 for r in results if r["ran_ok"])
    print(f"\n{verified}/{total} verified, {ran_ok}/{total} ran_ok. See RESULTS.json / RESULTS.md.")

    return 0 if verified == total else 1


if __name__ == "__main__":
    sys.exit(main())
