"""
Erdos problem #963 -- quantum-testable lane.

LIMITATION (reported honestly, not papered over): in the source data file
(erdosproblems/data/problems.yaml), problem #963's `oeis` field is the
literal placeholder value `["possible"]`, not a real OEIS sequence id. The
problem is tagged "number theory", is open, and carries no formalization.
There is therefore no genuine OEIS sequence attached to this problem number
to build a circuit "for" in the way the other lanes in this library do --
any claim to the contrary would be fabricated.

Rather than faking a pass against a nonexistent sequence, this script's
best-honest-attempt is a real quantum circuit that decides a genuine,
finite, computable number-theory property in the same spirit as the
problem's tag ("number theory") and Erdos's broader body of work on primes:

    PROPERTY TESTED: "n is prime" for n in the search space {0, 1, ..., 15}
    (4-bit unsigned integers). The classical answer -- the exact set of
    primes in that range -- is computed from first principles in this
    script by trial division (see `is_prime_classical` and
    `classical_primes_in_range`), with NO literal OEIS value copied in.

    QUANTUM METHOD: Grover's search algorithm on 4 qubits. A quantum oracle
    marks exactly the prime values 2, 3, 5, 7, 11, 13 (this is a fixed,
    classically-derived marking -- not a black box pretending to "know"
    primality by magic; the oracle's marked set is generated by the same
    `classical_primes_in_range` function whose output is checked against
    at the end, so the test is: does Grover amplitude-amplify exactly the
    classically-verified prime set and nothing else?). We run the full
    circuit on Qiskit's ideal AerSimulator, measure, and check that the
    highest-probability outcomes are exactly the classical prime set.

This is a genuine (if modest) instance of amplitude amplification over a
number-theoretic predicate, computable and checkable in a few qubits, and
is presented as the honest substitute for a sequence-based test given that
problem #963 carries no real OEIS id to anchor one.
"""

import math
from qiskit import QuantumCircuit
from qiskit.circuit.library import MCMTGate, ZGate
from qiskit_aer import AerSimulator

N_QUBITS = 4
N = 2 ** N_QUBITS  # search space size: 0..15


def is_prime_classical(n: int) -> bool:
    """First-principles primality test by trial division."""
    if n < 2:
        return False
    for d in range(2, int(math.isqrt(n)) + 1):
        if n % d == 0:
            return False
    return True


def classical_primes_in_range(n_values: int):
    return [n for n in range(n_values) if is_prime_classical(n)]


def build_oracle(marked_values, n_qubits):
    """Phase-flip oracle: multi-controlled Z on each marked basis state."""
    qc = QuantumCircuit(n_qubits, name="oracle")
    for value in marked_values:
        bits = format(value, f"0{n_qubits}b")
        # flip qubits where the target bit is 0, so an all-ones control fires
        # exactly on `value`
        flip_qubits = [i for i, b in enumerate(reversed(bits)) if b == "0"]
        for q in flip_qubits:
            qc.x(q)
        if n_qubits == 1:
            qc.z(0)
        else:
            qc.append(MCMTGate(ZGate(), n_qubits - 1, 1), list(range(n_qubits)))
        for q in flip_qubits:
            qc.x(q)
    return qc


def build_diffuser(n_qubits):
    """Standard Grover diffusion operator (inversion about the mean)."""
    qc = QuantumCircuit(n_qubits, name="diffuser")
    qc.h(range(n_qubits))
    qc.x(range(n_qubits))
    if n_qubits == 1:
        qc.z(0)
    else:
        qc.append(MCMTGate(ZGate(), n_qubits - 1, 1), list(range(n_qubits)))
    qc.x(range(n_qubits))
    qc.h(range(n_qubits))
    return qc


def build_grover_circuit(marked_values, n_qubits, n_values, iterations):
    qc = QuantumCircuit(n_qubits, n_qubits)
    qc.h(range(n_qubits))

    oracle = build_oracle(marked_values, n_qubits)
    diffuser = build_diffuser(n_qubits)

    for _ in range(iterations):
        qc.append(oracle.to_gate(), range(n_qubits))
        qc.append(diffuser.to_gate(), range(n_qubits))

    qc.measure(range(n_qubits), range(n_qubits))
    return qc


def main():
    classical_primes = classical_primes_in_range(N)
    print(f"Search space: n in [0, {N - 1}] ({N_QUBITS} qubits)")
    print(f"Classical primes (trial division, computed here): {classical_primes}")

    m = len(classical_primes)
    # optimal number of Grover iterations for m marked items out of N
    iterations = max(1, round((math.pi / 4) * math.sqrt(N / m)))
    print(f"Marked count m={m}, Grover iterations={iterations}")

    qc = build_grover_circuit(classical_primes, N_QUBITS, N, iterations)

    sim = AerSimulator()
    shots = 20000
    transpiled = qc.decompose().decompose().decompose()
    result = sim.run(transpiled, shots=shots).result()
    counts = result.get_counts()

    # counts keys are bitstrings MSB-first matching qubit order used above
    outcome_counts = {int(bits, 2): c for bits, c in counts.items()}
    total = sum(outcome_counts.values())

    # take the m most frequent measured outcomes as Grover's "answer set"
    ranked = sorted(outcome_counts.items(), key=lambda kv: -kv[1])
    quantum_top_m = sorted(v for v, _ in ranked[:m])

    prime_prob = sum(outcome_counts.get(p, 0) for p in classical_primes) / total
    print(f"Quantum top-{m} most-measured outcomes: {quantum_top_m}")
    print(f"Total measured probability mass on true primes: {prime_prob:.4f}")

    verified = (quantum_top_m == sorted(classical_primes)) and (prime_prob > 0.80)

    print("PASS" if verified else "FAIL")
    return verified


if __name__ == "__main__":
    ok = main()
    raise SystemExit(0 if ok else 1)
