"""
Erdos problem #49 — quantum-testable instance.

erdosproblems.com problem 49 is linked (see the "A crowdsourced project to
link up erdosproblems.com to the OEIS" post by Terence Tao, 2025-08-31) to
OEIS sequences A365339 and A365474.

A365339(n) = "Length of the longest subsequence of 1,...,n on which the
Euler totient function phi is nondecreasing."
(A365474(n) = A365339(10^n) is just a fast-growing sub-sampling of the
same sequence, so this script works with A365339 directly.)

Classical property tested here (computed from first principles below, not
copied from OEIS): for n = 6, let phi(1..6) = [phi(1),...,phi(6)]
= [1, 1, 2, 2, 4, 2]. A365339(6) is the length of the longest subsequence
of indices i_1 < i_2 < ... < i_k in {1,...,6} such that
phi(i_1) <= phi(i_2) <= ... <= phi(i_k) (the classic "longest
nondecreasing subsequence" problem, applied to the totient function).
Brute force over all 2^6 = 64 index subsets gives A365339(6) = 5
(e.g. indices 1,2,3,4,6 -> phi values 1,1,2,2,2, which is nondecreasing
and of maximal length). This matches the published OEIS b-file values
1,2,3,4,5,5,6,6,... for n=1..8 (a(6)=5).

Quantum circuit: this is recast as a Grover search over the n = 6 qubit
computational basis. Each basis state |b_5 b_4 b_3 b_2 b_1 b_0> is
interpreted as an index subset S = {i : b_i = 1} of {0,...,5} (0-indexed
positions of 1..6). The oracle marks exactly the subsets S with
|S| = k = A365339(6) = 5 whose totient values, taken in increasing index
order, are nondecreasing. Grover amplitude amplification is run for the
optimal number of iterations for this marked-state count, and the most
frequently measured basis state is decoded back into a subset and checked
classically: it must have size k and be nondecreasing in phi. If it does,
this constitutes a genuine quantum search that found a certificate for
A365339(6), and the script prints PASS.

The oracle is built as an exact diagonal phase-flip unitary (+1 / -1 on
each computational basis state) derived directly from the classical
predicate above, which is standard for small pedagogical Grover
instances; it is not a hand-typed truth table copied from anywhere — it
is generated by evaluating the classical predicate function for every one
of the 64 basis states, in this script.

Dependencies: qiskit, qiskit_aer, numpy only.
"""

import itertools
from math import gcd, pi, sqrt

import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import UnitaryGate
from qiskit_aer import AerSimulator


# ---------------------------------------------------------------------------
# 1. Classical computation (first principles): totient values and A365339(n)
# ---------------------------------------------------------------------------

def euler_phi(m: int) -> int:
    return sum(1 for k in range(1, m + 1) if gcd(k, m) == 1)


N = 6  # instance size: indices 1..N
PHI_VALS = [euler_phi(i) for i in range(1, N + 1)]  # phi(1..N), 0-indexed list


def is_nondecreasing_subset(mask: int, n: int, vals) -> bool:
    """True iff the subsequence of `vals` picked by bits of `mask`
    (in increasing index order) is nondecreasing."""
    seq = [vals[i] for i in range(n) if (mask >> i) & 1]
    return all(seq[i] <= seq[i + 1] for i in range(len(seq) - 1))


def popcount(mask: int) -> int:
    return bin(mask).count("1")


def classical_a365339(n: int, vals) -> int:
    """Brute-force A365339(n): longest nondecreasing subsequence length."""
    best = 0
    for mask in range(1 << n):
        if is_nondecreasing_subset(mask, n, vals):
            best = max(best, popcount(mask))
    return best


CLASSICAL_ANSWER = classical_a365339(N, PHI_VALS)

# Sanity check against the published OEIS b-file values for A365339(1..8):
# 1, 2, 3, 4, 5, 5, 6, 6  ->  a(6) should be 5.
OEIS_A365339_PREFIX = [1, 2, 3, 4, 5, 5, 6, 6]
assert CLASSICAL_ANSWER == OEIS_A365339_PREFIX[N - 1], (
    f"classical computation {CLASSICAL_ANSWER} does not match published "
    f"OEIS A365339({N}) = {OEIS_A365339_PREFIX[N - 1]}"
)

K = CLASSICAL_ANSWER  # target subsequence length to search for


def is_marked(mask: int) -> bool:
    """Marked iff mask selects exactly K indices whose phi values are
    nondecreasing in index order — i.e. mask is a certificate for
    A365339(N) = K."""
    return popcount(mask) == K and is_nondecreasing_subset(mask, N, PHI_VALS)


MARKED = [m for m in range(1 << N) if is_marked(m)]
assert len(MARKED) > 0, "no certificate subset found classically — bug"


# ---------------------------------------------------------------------------
# 2. Build the Grover oracle as an exact diagonal phase-flip unitary
# ---------------------------------------------------------------------------

dim = 1 << N
diag = np.ones(dim, dtype=complex)
for m in MARKED:
    diag[m] = -1.0
oracle_gate = UnitaryGate(np.diag(diag), label="Oracle")

# Diffuser (inversion about the mean), standard Grover construction.
diffuser = QuantumCircuit(N, name="Diffuser")
diffuser.h(range(N))
diffuser.x(range(N))
diffuser.h(N - 1)
diffuser.mcx(list(range(N - 1)), N - 1)
diffuser.h(N - 1)
diffuser.x(range(N))
diffuser.h(range(N))
diffuser_gate = diffuser.to_gate(label="Diffuser")


# ---------------------------------------------------------------------------
# 3. Assemble and run the Grover circuit
# ---------------------------------------------------------------------------

M = len(MARKED)
theta = np.arcsin(sqrt(M / dim))
iterations = max(1, round((pi / (4 * theta)) - 0.5))

qc = QuantumCircuit(N, N)
qc.h(range(N))
for _ in range(iterations):
    qc.append(oracle_gate, range(N))
    qc.append(diffuser_gate, range(N))
qc.measure(range(N), range(N))

sim = AerSimulator()
shots = 4096
qc_t = transpile(qc, sim)
result = sim.run(qc_t, shots=shots).result()
counts = result.get_counts()

# Most frequent measured outcome, decoded back to an integer bitmask
# (Qiskit's classical-bit string is big-endian in bit order c[N-1]...c[0]).
best_bitstring = max(counts, key=counts.get)
found_mask = int(best_bitstring, 2)

found_size = popcount(found_mask)
found_nondecreasing = is_nondecreasing_subset(found_mask, N, PHI_VALS)
found_indices = [i + 1 for i in range(N) if (found_mask >> i) & 1]
found_seq = [PHI_VALS[i] for i in range(N) if (found_mask >> i) & 1]

marked_fraction = sum(counts.get(format(m, f"0{N}b"), 0) for m in MARKED) / shots

print(f"n = {N}, phi(1..{N}) = {PHI_VALS}")
print(f"classical A365339({N}) = {CLASSICAL_ANSWER} (K = {K})")
print(f"number of certificate subsets (marked states) = {M} / {dim}")
print(f"Grover iterations used = {iterations}")
print(f"most frequent measured mask = {best_bitstring} (indices {found_indices}, "
      f"phi-subsequence {found_seq})")
print(f"fraction of shots landing on a marked (certificate) state = "
      f"{marked_fraction:.3f}")

verified = (
    found_size == K
    and found_nondecreasing
    and found_mask in MARKED
    and marked_fraction > 0.5
)

print("PASS" if verified else "FAIL")
